# --- ソースモデル情報 ---
source_structure_file: "./data/input/Bi/PBE/spinless/POSCAR"
source_hr_file: "./data/input/Bi/PBE/spinless/wannier90_hr.dat"
source_win_file: "./data/input/Bi/PBE/spinless/wannier90.win" 

# --- ターゲット構造情報 ---
target_structure_file: null
target_projection: null
output_hr_file: "./data/output/Bi/PBE/spinless/mapped_hr.dat"

# --- 一般設定 ---
spin: false
fermi_energy: 2.9478

# --- 解析オプション ---
distance_threshold: 1.0e-9
zero_hop_threshold: 1.0e-9
hopping_cutoff_distance: 6.5
use_hermitian_symmetrization: true
use_symmetry_averaging: false
fit_type: "linear" # "exp", "gaussian", "linear"

# --- 方向依存性オプション ---
# use_auto_direction_clusters: true
# max_direction_clusters: 8

# --- 検証オプション ---
run_plotting: true
run_validation: true
compare_parameters: true

# --- デバッグ用オプション
use_ungrouped_interpolation: true